// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.1
// source: protodb.proto

package protodb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FieldDbType int32

const (
	// auto match db type if DbTypeStr not set
	// pb type -> db type
	// bool -> bool
	// string -> text
	// int32 -> int
	// int64,uint32 -> bigint
	// float -> float
	// double -> double precision
	// bytes -> bytea
	FieldDbType_AutoMatch FieldDbType = 0
	FieldDbType_BOOL      FieldDbType = 1
	FieldDbType_INT32     FieldDbType = 2
	FieldDbType_INT64     FieldDbType = 3
	FieldDbType_FLOAT     FieldDbType = 4
	FieldDbType_DOUBLE    FieldDbType = 5
	FieldDbType_TEXT      FieldDbType = 6
	FieldDbType_JSONB     FieldDbType = 7
	FieldDbType_UUID      FieldDbType = 8
	FieldDbType_TIMESTAMP FieldDbType = 9
	FieldDbType_DATE      FieldDbType = 10
	FieldDbType_BYTEA     FieldDbType = 11
	// ipv4 or ipv6 address
	FieldDbType_INET   FieldDbType = 12
	FieldDbType_UINT32 FieldDbType = 13
)

// Enum value maps for FieldDbType.
var (
	FieldDbType_name = map[int32]string{
		0:  "AutoMatch",
		1:  "BOOL",
		2:  "INT32",
		3:  "INT64",
		4:  "FLOAT",
		5:  "DOUBLE",
		6:  "TEXT",
		7:  "JSONB",
		8:  "UUID",
		9:  "TIMESTAMP",
		10: "DATE",
		11: "BYTEA",
		12: "INET",
		13: "UINT32",
	}
	FieldDbType_value = map[string]int32{
		"AutoMatch": 0,
		"BOOL":      1,
		"INT32":     2,
		"INT64":     3,
		"FLOAT":     4,
		"DOUBLE":    5,
		"TEXT":      6,
		"JSONB":     7,
		"UUID":      8,
		"TIMESTAMP": 9,
		"DATE":      10,
		"BYTEA":     11,
		"INET":      12,
		"UINT32":    13,
	}
)

func (x FieldDbType) Enum() *FieldDbType {
	p := new(FieldDbType)
	*p = x
	return p
}

func (x FieldDbType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FieldDbType) Descriptor() protoreflect.EnumDescriptor {
	return file_protodb_proto_enumTypes[0].Descriptor()
}

func (FieldDbType) Type() protoreflect.EnumType {
	return &file_protodb_proto_enumTypes[0]
}

func (x FieldDbType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FieldDbType.Descriptor instead.
func (FieldDbType) EnumDescriptor() ([]byte, []int) {
	return file_protodb_proto_rawDescGZIP(), []int{0}
}

// crud api code
type CrudReqCode int32

const (
	CrudReqCode_INSERT        CrudReqCode = 0
	CrudReqCode_UPDATE        CrudReqCode = 1
	CrudReqCode_PARTIALUPDATE CrudReqCode = 2
	CrudReqCode_DELETE        CrudReqCode = 3
	CrudReqCode_SELECTONE     CrudReqCode = 4
	CrudReqCode_QUERY         CrudReqCode = 5
)

// Enum value maps for CrudReqCode.
var (
	CrudReqCode_name = map[int32]string{
		0: "INSERT",
		1: "UPDATE",
		2: "PARTIALUPDATE",
		3: "DELETE",
		4: "SELECTONE",
		5: "QUERY",
	}
	CrudReqCode_value = map[string]int32{
		"INSERT":        0,
		"UPDATE":        1,
		"PARTIALUPDATE": 2,
		"DELETE":        3,
		"SELECTONE":     4,
		"QUERY":         5,
	}
)

func (x CrudReqCode) Enum() *CrudReqCode {
	p := new(CrudReqCode)
	*p = x
	return p
}

func (x CrudReqCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CrudReqCode) Descriptor() protoreflect.EnumDescriptor {
	return file_protodb_proto_enumTypes[1].Descriptor()
}

func (CrudReqCode) Type() protoreflect.EnumType {
	return &file_protodb_proto_enumTypes[1]
}

func (x CrudReqCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CrudReqCode.Descriptor instead.
func (CrudReqCode) EnumDescriptor() ([]byte, []int) {
	return file_protodb_proto_rawDescGZIP(), []int{1}
}

// crud result type for return
type CrudResultType int32

const (
	// only info dml result(affected rows)
	CrudResultType_DMLResult CrudResultType = 0
	// return new row as msg, selectone use this too
	CrudResultType_NewMsg CrudResultType = 1
	// return old row as msg and new row as msg
	CrudResultType_OldMsgAndNewMsg CrudResultType = 2
)

// Enum value maps for CrudResultType.
var (
	CrudResultType_name = map[int32]string{
		0: "DMLResult",
		1: "NewMsg",
		2: "OldMsgAndNewMsg",
	}
	CrudResultType_value = map[string]int32{
		"DMLResult":       0,
		"NewMsg":          1,
		"OldMsgAndNewMsg": 2,
	}
)

func (x CrudResultType) Enum() *CrudResultType {
	p := new(CrudResultType)
	*p = x
	return p
}

func (x CrudResultType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CrudResultType) Descriptor() protoreflect.EnumDescriptor {
	return file_protodb_proto_enumTypes[2].Descriptor()
}

func (CrudResultType) Type() protoreflect.EnumType {
	return &file_protodb_proto_enumTypes[2]
}

func (x CrudResultType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CrudResultType.Descriptor instead.
func (CrudResultType) EnumDescriptor() ([]byte, []int) {
	return file_protodb_proto_rawDescGZIP(), []int{2}
}

// where operator
type WhereOperator int32

const (
	// unknown
	WhereOperator_WOP_UNKNOWN WhereOperator = 0
	// > greater than
	WhereOperator_WOP_GT WhereOperator = 1
	// < less than
	WhereOperator_WOP_LT WhereOperator = 2
	// >= greater than or equal
	WhereOperator_WOP_GTE WhereOperator = 3
	// <= less than or equal
	WhereOperator_WOP_LTE WhereOperator = 4
	// like
	WhereOperator_WOP_LIKE WhereOperator = 5
	// equal
	WhereOperator_WOP_EQ WhereOperator = 6
	// array contains element
	WhereOperator_WOP_CONTAINS WhereOperator = 7
	// array overlaps given array
	WhereOperator_WOP_OVERLAP WhereOperator = 8
	// array contains all elements of given array
	WhereOperator_WOP_CONTAINS_ALL WhereOperator = 9
	// length greater than
	WhereOperator_WOP_LEN_GT  WhereOperator = 10
	WhereOperator_WOP_LEN_GTE WhereOperator = 11
	WhereOperator_WOP_LEN_LT  WhereOperator = 12
	WhereOperator_WOP_LEN_LTE WhereOperator = 13
	// map has key
	WhereOperator_WOP_HAS_KEY WhereOperator = 14
)

// Enum value maps for WhereOperator.
var (
	WhereOperator_name = map[int32]string{
		0:  "WOP_UNKNOWN",
		1:  "WOP_GT",
		2:  "WOP_LT",
		3:  "WOP_GTE",
		4:  "WOP_LTE",
		5:  "WOP_LIKE",
		6:  "WOP_EQ",
		7:  "WOP_CONTAINS",
		8:  "WOP_OVERLAP",
		9:  "WOP_CONTAINS_ALL",
		10: "WOP_LEN_GT",
		11: "WOP_LEN_GTE",
		12: "WOP_LEN_LT",
		13: "WOP_LEN_LTE",
		14: "WOP_HAS_KEY",
	}
	WhereOperator_value = map[string]int32{
		"WOP_UNKNOWN":      0,
		"WOP_GT":           1,
		"WOP_LT":           2,
		"WOP_GTE":          3,
		"WOP_LTE":          4,
		"WOP_LIKE":         5,
		"WOP_EQ":           6,
		"WOP_CONTAINS":     7,
		"WOP_OVERLAP":      8,
		"WOP_CONTAINS_ALL": 9,
		"WOP_LEN_GT":       10,
		"WOP_LEN_GTE":      11,
		"WOP_LEN_LT":       12,
		"WOP_LEN_LTE":      13,
		"WOP_HAS_KEY":      14,
	}
)

func (x WhereOperator) Enum() *WhereOperator {
	p := new(WhereOperator)
	*p = x
	return p
}

func (x WhereOperator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WhereOperator) Descriptor() protoreflect.EnumDescriptor {
	return file_protodb_proto_enumTypes[3].Descriptor()
}

func (WhereOperator) Type() protoreflect.EnumType {
	return &file_protodb_proto_enumTypes[3]
}

func (x WhereOperator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WhereOperator.Descriptor instead.
func (WhereOperator) EnumDescriptor() ([]byte, []int) {
	return file_protodb_proto_rawDescGZIP(), []int{3}
}

type PDBFile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name style(msg & field)
	// empty='go': default, go name style, better performance in crud operation in
	// go (like: UserName) 'snake': snake name style (like: user_name)
	NameStyle string `protobuf:"bytes,1,opt,name=NameStyle,proto3" json:"NameStyle,omitempty"`
	// comment for file
	Comment       []string `protobuf:"bytes,2,rep,name=Comment,proto3" json:"Comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PDBFile) Reset() {
	*x = PDBFile{}
	mi := &file_protodb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PDBFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PDBFile) ProtoMessage() {}

func (x *PDBFile) ProtoReflect() protoreflect.Message {
	mi := &file_protodb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PDBFile.ProtoReflect.Descriptor instead.
func (*PDBFile) Descriptor() ([]byte, []int) {
	return file_protodb_proto_rawDescGZIP(), []int{0}
}

func (x *PDBFile) GetNameStyle() string {
	if x != nil {
		return x.NameStyle
	}
	return ""
}

func (x *PDBFile) GetComment() []string {
	if x != nil {
		return x.Comment
	}
	return nil
}

type PDBMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// comment for table
	Comment []string `protobuf:"bytes,1,rep,name=Comment,proto3" json:"Comment,omitempty"`
	// sql prepends before create table
	SQLPrepend []string `protobuf:"bytes,2,rep,name=SQLPrepend,proto3" json:"SQLPrepend,omitempty"`
	// sql appends before )
	SQLAppend []string `protobuf:"bytes,3,rep,name=SQLAppend,proto3" json:"SQLAppend,omitempty"`
	// sql appends after ) before ;
	SQLAppendsAfter []string `protobuf:"bytes,4,rep,name=SQLAppendsAfter,proto3" json:"SQLAppendsAfter,omitempty"`
	// sql appends after ;
	SQLAppendsEnd []string `protobuf:"bytes,5,rep,name=SQLAppendsEnd,proto3" json:"SQLAppendsEnd,omitempty"`
	// generate proto msg { {msg}}List in  xxx.list.proto
	// 0: auto if msg name start with db then generate { {msg}}List
	// 1: always generate { {msg}}List
	// 4: never generate { {msg}}List
	MsgList int32 `protobuf:"varint,6,opt,name=MsgList,proto3" json:"MsgList,omitempty"`
	// do not generate db table for this message
	NotDB bool `protobuf:"varint,7,opt,name=NotDB,proto3" json:"NotDB,omitempty"`
	// sql for migrate table
	SQLMigrate    []string `protobuf:"bytes,8,rep,name=SQLMigrate,proto3" json:"SQLMigrate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PDBMsg) Reset() {
	*x = PDBMsg{}
	mi := &file_protodb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PDBMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PDBMsg) ProtoMessage() {}

func (x *PDBMsg) ProtoReflect() protoreflect.Message {
	mi := &file_protodb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PDBMsg.ProtoReflect.Descriptor instead.
func (*PDBMsg) Descriptor() ([]byte, []int) {
	return file_protodb_proto_rawDescGZIP(), []int{1}
}

func (x *PDBMsg) GetComment() []string {
	if x != nil {
		return x.Comment
	}
	return nil
}

func (x *PDBMsg) GetSQLPrepend() []string {
	if x != nil {
		return x.SQLPrepend
	}
	return nil
}

func (x *PDBMsg) GetSQLAppend() []string {
	if x != nil {
		return x.SQLAppend
	}
	return nil
}

func (x *PDBMsg) GetSQLAppendsAfter() []string {
	if x != nil {
		return x.SQLAppendsAfter
	}
	return nil
}

func (x *PDBMsg) GetSQLAppendsEnd() []string {
	if x != nil {
		return x.SQLAppendsEnd
	}
	return nil
}

func (x *PDBMsg) GetMsgList() int32 {
	if x != nil {
		return x.MsgList
	}
	return 0
}

func (x *PDBMsg) GetNotDB() bool {
	if x != nil {
		return x.NotDB
	}
	return false
}

func (x *PDBMsg) GetSQLMigrate() []string {
	if x != nil {
		return x.SQLMigrate
	}
	return nil
}

type PDBField struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// do not generate db field in create table
	// when in update, do not update this field
	NotDB bool `protobuf:"varint,1,opt,name=NotDB,proto3" json:"NotDB,omitempty"`
	// is primary key
	Primary bool `protobuf:"varint,2,opt,name=Primary,proto3" json:"Primary,omitempty"`
	// is unique key, if the unique include multiple columns, specify the UniqueName
	Unique bool `protobuf:"varint,3,opt,name=Unique,proto3" json:"Unique,omitempty"`
	// is not null
	NotNull bool `protobuf:"varint,4,opt,name=NotNull,proto3" json:"NotNull,omitempty"`
	// reference to other table, sql like:  REFERENCES other_table(other_field)
	Reference string `protobuf:"bytes,5,opt,name=Reference,proto3" json:"Reference,omitempty"`
	// default value
	DefaultValue string `protobuf:"bytes,6,opt,name=DefaultValue,proto3" json:"DefaultValue,omitempty"`
	// append sql before ,
	SQLAppend []string `protobuf:"bytes,7,rep,name=SQLAppend,proto3" json:"SQLAppend,omitempty"`
	// append sql after ,
	SQLAppendsEnd []string `protobuf:"bytes,8,rep,name=SQLAppendsEnd,proto3" json:"SQLAppendsEnd,omitempty"`
	// db no update
	// when in update, do not update this field, for example, create time
	NoUpdate bool `protobuf:"varint,9,opt,name=NoUpdate,proto3" json:"NoUpdate,omitempty"`
	// serial type 0:not serial type 2:smallint(serial2) 4:integer(serial4) 8:bigint(serial8)
	// strong advice not use serial type,it's hard in distributed system
	SerialType int32 `protobuf:"varint,10,opt,name=SerialType,proto3" json:"SerialType,omitempty"`
	// db type
	DbType FieldDbType `protobuf:"varint,11,opt,name=DbType,proto3,enum=protodb.FieldDbType" json:"DbType,omitempty"`
	// use custom db type when DbType is not good fit
	DbTypeStr string `protobuf:"bytes,12,opt,name=DbTypeStr,proto3" json:"DbTypeStr,omitempty"`
	// zero value treat as null for insert,update, especially for reference field
	ZeroAsNull bool `protobuf:"varint,13,opt,name=ZeroAsNull,proto3" json:"ZeroAsNull,omitempty"`
	// db no insert
	// when in insert, do not insert this field, for example, database has default value
	NoInsert bool `protobuf:"varint,14,opt,name=NoInsert,proto3" json:"NoInsert,omitempty"`
	// comment for field
	Comment []string `protobuf:"bytes,15,rep,name=Comment,proto3" json:"Comment,omitempty"`
	// unique group name
	// when a unique constrain include multiple column, specify the a group name for it
	UniqueName    string `protobuf:"bytes,16,opt,name=UniqueName,proto3" json:"UniqueName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PDBField) Reset() {
	*x = PDBField{}
	mi := &file_protodb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PDBField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PDBField) ProtoMessage() {}

func (x *PDBField) ProtoReflect() protoreflect.Message {
	mi := &file_protodb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PDBField.ProtoReflect.Descriptor instead.
func (*PDBField) Descriptor() ([]byte, []int) {
	return file_protodb_proto_rawDescGZIP(), []int{2}
}

func (x *PDBField) GetNotDB() bool {
	if x != nil {
		return x.NotDB
	}
	return false
}

func (x *PDBField) GetPrimary() bool {
	if x != nil {
		return x.Primary
	}
	return false
}

func (x *PDBField) GetUnique() bool {
	if x != nil {
		return x.Unique
	}
	return false
}

func (x *PDBField) GetNotNull() bool {
	if x != nil {
		return x.NotNull
	}
	return false
}

func (x *PDBField) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *PDBField) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *PDBField) GetSQLAppend() []string {
	if x != nil {
		return x.SQLAppend
	}
	return nil
}

func (x *PDBField) GetSQLAppendsEnd() []string {
	if x != nil {
		return x.SQLAppendsEnd
	}
	return nil
}

func (x *PDBField) GetNoUpdate() bool {
	if x != nil {
		return x.NoUpdate
	}
	return false
}

func (x *PDBField) GetSerialType() int32 {
	if x != nil {
		return x.SerialType
	}
	return 0
}

func (x *PDBField) GetDbType() FieldDbType {
	if x != nil {
		return x.DbType
	}
	return FieldDbType_AutoMatch
}

func (x *PDBField) GetDbTypeStr() string {
	if x != nil {
		return x.DbTypeStr
	}
	return ""
}

func (x *PDBField) GetZeroAsNull() bool {
	if x != nil {
		return x.ZeroAsNull
	}
	return false
}

func (x *PDBField) GetNoInsert() bool {
	if x != nil {
		return x.NoInsert
	}
	return false
}

func (x *PDBField) GetComment() []string {
	if x != nil {
		return x.Comment
	}
	return nil
}

func (x *PDBField) GetUniqueName() string {
	if x != nil {
		return x.UniqueName
	}
	return ""
}

// crud request
type CrudReq struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Code       CrudReqCode            `protobuf:"varint,1,opt,name=Code,proto3,enum=protodb.CrudReqCode" json:"Code,omitempty"`
	ResultType CrudResultType         `protobuf:"varint,2,opt,name=ResultType,proto3,enum=protodb.CrudResultType" json:"ResultType,omitempty"`
	SchemeName string                 `protobuf:"bytes,3,opt,name=SchemeName,proto3" json:"SchemeName,omitempty"`
	TableName  string                 `protobuf:"bytes,4,opt,name=TableName,proto3" json:"TableName,omitempty"`
	MsgBytes   []byte                 `protobuf:"bytes,5,opt,name=MsgBytes,proto3" json:"MsgBytes,omitempty"`
	// msg format 0:protobuf 1:protobuf json
	MsgFormat           int32    `protobuf:"varint,6,opt,name=MsgFormat,proto3" json:"MsgFormat,omitempty"`
	MsgLastFieldNo      int32    `protobuf:"varint,7,opt,name=MsgLastFieldNo,proto3" json:"MsgLastFieldNo,omitempty"`
	PartialUpdateFields []string `protobuf:"bytes,8,rep,name=PartialUpdateFields,proto3" json:"PartialUpdateFields,omitempty"`
	SelectResultFields  []string `protobuf:"bytes,9,rep,name=SelectResultFields,proto3" json:"SelectResultFields,omitempty"`
	SelectOneKeyFields  []string `protobuf:"bytes,10,rep,name=SelectOneKeyFields,proto3" json:"SelectOneKeyFields,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CrudReq) Reset() {
	*x = CrudReq{}
	mi := &file_protodb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrudReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrudReq) ProtoMessage() {}

func (x *CrudReq) ProtoReflect() protoreflect.Message {
	mi := &file_protodb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrudReq.ProtoReflect.Descriptor instead.
func (*CrudReq) Descriptor() ([]byte, []int) {
	return file_protodb_proto_rawDescGZIP(), []int{3}
}

func (x *CrudReq) GetCode() CrudReqCode {
	if x != nil {
		return x.Code
	}
	return CrudReqCode_INSERT
}

func (x *CrudReq) GetResultType() CrudResultType {
	if x != nil {
		return x.ResultType
	}
	return CrudResultType_DMLResult
}

func (x *CrudReq) GetSchemeName() string {
	if x != nil {
		return x.SchemeName
	}
	return ""
}

func (x *CrudReq) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *CrudReq) GetMsgBytes() []byte {
	if x != nil {
		return x.MsgBytes
	}
	return nil
}

func (x *CrudReq) GetMsgFormat() int32 {
	if x != nil {
		return x.MsgFormat
	}
	return 0
}

func (x *CrudReq) GetMsgLastFieldNo() int32 {
	if x != nil {
		return x.MsgLastFieldNo
	}
	return 0
}

func (x *CrudReq) GetPartialUpdateFields() []string {
	if x != nil {
		return x.PartialUpdateFields
	}
	return nil
}

func (x *CrudReq) GetSelectResultFields() []string {
	if x != nil {
		return x.SelectResultFields
	}
	return nil
}

func (x *CrudReq) GetSelectOneKeyFields() []string {
	if x != nil {
		return x.SelectOneKeyFields
	}
	return nil
}

// Crud response
type CrudResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RowsAffected in dml operation
	RowsAffected int64 `protobuf:"varint,1,opt,name=RowsAffected,proto3" json:"RowsAffected,omitempty"`
	// err info when error happened
	ErrInfo string `protobuf:"bytes,2,opt,name=ErrInfo,proto3" json:"ErrInfo,omitempty"`
	// old row as msg
	OldMsgBytes []byte `protobuf:"bytes,3,opt,name=OldMsgBytes,proto3" json:"OldMsgBytes,omitempty"`
	// new row as msg
	NewMsgBytes []byte `protobuf:"bytes,4,opt,name=NewMsgBytes,proto3" json:"NewMsgBytes,omitempty"`
	// msg format 0:protobuf 1:protobuf json
	MsgFormat     int32 `protobuf:"varint,8,opt,name=MsgFormat,proto3" json:"MsgFormat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrudResp) Reset() {
	*x = CrudResp{}
	mi := &file_protodb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrudResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrudResp) ProtoMessage() {}

func (x *CrudResp) ProtoReflect() protoreflect.Message {
	mi := &file_protodb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrudResp.ProtoReflect.Descriptor instead.
func (*CrudResp) Descriptor() ([]byte, []int) {
	return file_protodb_proto_rawDescGZIP(), []int{4}
}

func (x *CrudResp) GetRowsAffected() int64 {
	if x != nil {
		return x.RowsAffected
	}
	return 0
}

func (x *CrudResp) GetErrInfo() string {
	if x != nil {
		return x.ErrInfo
	}
	return ""
}

func (x *CrudResp) GetOldMsgBytes() []byte {
	if x != nil {
		return x.OldMsgBytes
	}
	return nil
}

func (x *CrudResp) GetNewMsgBytes() []byte {
	if x != nil {
		return x.NewMsgBytes
	}
	return nil
}

func (x *CrudResp) GetMsgFormat() int32 {
	if x != nil {
		return x.MsgFormat
	}
	return 0
}

type TableQueryReq struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	SchemeName string                 `protobuf:"bytes,1,opt,name=SchemeName,proto3" json:"SchemeName,omitempty"`
	TableName  string                 `protobuf:"bytes,2,opt,name=TableName,proto3" json:"TableName,omitempty"`
	// result column names, need same as proto msg field name
	ResultColumnNames []string `protobuf:"bytes,3,rep,name=ResultColumnNames,proto3" json:"ResultColumnNames,omitempty"`
	// Fieldname == Value
	Where map[string]string `protobuf:"bytes,4,rep,name=Where,proto3" json:"Where,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// limit 0:no limit
	Limit  int32 `protobuf:"varint,5,opt,name=Limit,proto3" json:"Limit,omitempty"`
	Offset int64 `protobuf:"varint,6,opt,name=Offset,proto3" json:"Offset,omitempty"`
	// prefer batch size
	PreferBatchSize int32 `protobuf:"varint,7,opt,name=PreferBatchSize,proto3" json:"PreferBatchSize,omitempty"`
	// msg format 0:protobuf 1:protobuf json
	MsgFormat int32 `protobuf:"varint,8,opt,name=MsgFormat,proto3" json:"MsgFormat,omitempty"`
	// where2 field operator, fieldname -> op
	Where2Operator map[string]WhereOperator `protobuf:"bytes,9,rep,name=Where2Operator,proto3" json:"Where2Operator,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=protodb.WhereOperator"`
	// where2 field value, fieldname -> value
	Where2        map[string]string `protobuf:"bytes,10,rep,name=Where2,proto3" json:"Where2,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableQueryReq) Reset() {
	*x = TableQueryReq{}
	mi := &file_protodb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableQueryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableQueryReq) ProtoMessage() {}

func (x *TableQueryReq) ProtoReflect() protoreflect.Message {
	mi := &file_protodb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableQueryReq.ProtoReflect.Descriptor instead.
func (*TableQueryReq) Descriptor() ([]byte, []int) {
	return file_protodb_proto_rawDescGZIP(), []int{5}
}

func (x *TableQueryReq) GetSchemeName() string {
	if x != nil {
		return x.SchemeName
	}
	return ""
}

func (x *TableQueryReq) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *TableQueryReq) GetResultColumnNames() []string {
	if x != nil {
		return x.ResultColumnNames
	}
	return nil
}

func (x *TableQueryReq) GetWhere() map[string]string {
	if x != nil {
		return x.Where
	}
	return nil
}

func (x *TableQueryReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *TableQueryReq) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *TableQueryReq) GetPreferBatchSize() int32 {
	if x != nil {
		return x.PreferBatchSize
	}
	return 0
}

func (x *TableQueryReq) GetMsgFormat() int32 {
	if x != nil {
		return x.MsgFormat
	}
	return 0
}

func (x *TableQueryReq) GetWhere2Operator() map[string]WhereOperator {
	if x != nil {
		return x.Where2Operator
	}
	return nil
}

func (x *TableQueryReq) GetWhere2() map[string]string {
	if x != nil {
		return x.Where2
	}
	return nil
}

type QueryResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// response batch no, start from 0
	ResponseNo int64 `protobuf:"varint,1,opt,name=ResponseNo,proto3" json:"ResponseNo,omitempty"`
	// if it is last response
	ResponseEnd bool `protobuf:"varint,2,opt,name=ResponseEnd,proto3" json:"ResponseEnd,omitempty"`
	// err info when error happened
	ErrInfo  string   `protobuf:"bytes,3,opt,name=ErrInfo,proto3" json:"ErrInfo,omitempty"`
	MsgBytes [][]byte `protobuf:"bytes,4,rep,name=MsgBytes,proto3" json:"MsgBytes,omitempty"`
	// msg format 0:protobuf 1:protobuf json
	MsgFormat     int32 `protobuf:"varint,8,opt,name=MsgFormat,proto3" json:"MsgFormat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResp) Reset() {
	*x = QueryResp{}
	mi := &file_protodb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResp) ProtoMessage() {}

func (x *QueryResp) ProtoReflect() protoreflect.Message {
	mi := &file_protodb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResp.ProtoReflect.Descriptor instead.
func (*QueryResp) Descriptor() ([]byte, []int) {
	return file_protodb_proto_rawDescGZIP(), []int{6}
}

func (x *QueryResp) GetResponseNo() int64 {
	if x != nil {
		return x.ResponseNo
	}
	return 0
}

func (x *QueryResp) GetResponseEnd() bool {
	if x != nil {
		return x.ResponseEnd
	}
	return false
}

func (x *QueryResp) GetErrInfo() string {
	if x != nil {
		return x.ErrInfo
	}
	return ""
}

func (x *QueryResp) GetMsgBytes() [][]byte {
	if x != nil {
		return x.MsgBytes
	}
	return nil
}

func (x *QueryResp) GetMsgFormat() int32 {
	if x != nil {
		return x.MsgFormat
	}
	return 0
}

type QueryReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// history sql
	QueryName string `protobuf:"bytes,1,opt,name=QueryName,proto3" json:"QueryName,omitempty"`
	// result column names, need same as proto msg field name
	ResultColumnNames []string `protobuf:"bytes,3,rep,name=ResultColumnNames,proto3" json:"ResultColumnNames,omitempty"`
	// sql where condition Fieldname == Value
	Where map[string]string `protobuf:"bytes,4,rep,name=Where,proto3" json:"Where,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// custom where protobuf msg bytes
	WhereMsgBytes []byte `protobuf:"bytes,5,opt,name=WhereMsgBytes,proto3" json:"WhereMsgBytes,omitempty"`
	// limit 0:no limit
	Limit  int32 `protobuf:"varint,6,opt,name=Limit,proto3" json:"Limit,omitempty"`
	Offset int64 `protobuf:"varint,7,opt,name=Offset,proto3" json:"Offset,omitempty"`
	// prefer batch size
	PreferBatchSize int32 `protobuf:"varint,8,opt,name=PreferBatchSize,proto3" json:"PreferBatchSize,omitempty"`
	// msg format 0:protobuf 1:protobuf json
	MsgFormat int32 `protobuf:"varint,9,opt,name=MsgFormat,proto3" json:"MsgFormat,omitempty"`
	// where2 field operator, fieldname op
	Where2Operator map[string]WhereOperator `protobuf:"bytes,10,rep,name=Where2Operator,proto3" json:"Where2Operator,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=protodb.WhereOperator"`
	// where2 field value, fieldname op value
	Where2        map[string]string `protobuf:"bytes,11,rep,name=Where2,proto3" json:"Where2,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryReq) Reset() {
	*x = QueryReq{}
	mi := &file_protodb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryReq) ProtoMessage() {}

func (x *QueryReq) ProtoReflect() protoreflect.Message {
	mi := &file_protodb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryReq.ProtoReflect.Descriptor instead.
func (*QueryReq) Descriptor() ([]byte, []int) {
	return file_protodb_proto_rawDescGZIP(), []int{7}
}

func (x *QueryReq) GetQueryName() string {
	if x != nil {
		return x.QueryName
	}
	return ""
}

func (x *QueryReq) GetResultColumnNames() []string {
	if x != nil {
		return x.ResultColumnNames
	}
	return nil
}

func (x *QueryReq) GetWhere() map[string]string {
	if x != nil {
		return x.Where
	}
	return nil
}

func (x *QueryReq) GetWhereMsgBytes() []byte {
	if x != nil {
		return x.WhereMsgBytes
	}
	return nil
}

func (x *QueryReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryReq) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *QueryReq) GetPreferBatchSize() int32 {
	if x != nil {
		return x.PreferBatchSize
	}
	return 0
}

func (x *QueryReq) GetMsgFormat() int32 {
	if x != nil {
		return x.MsgFormat
	}
	return 0
}

func (x *QueryReq) GetWhere2Operator() map[string]WhereOperator {
	if x != nil {
		return x.Where2Operator
	}
	return nil
}

func (x *QueryReq) GetWhere2() map[string]string {
	if x != nil {
		return x.Where2
	}
	return nil
}

var file_protodb_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*PDBFile)(nil),
		Field:         1888,
		Name:          "protodb.pdbf",
		Tag:           "bytes,1888,opt,name=pdbf",
		Filename:      "protodb.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*PDBMsg)(nil),
		Field:         1888,
		Name:          "protodb.pdbm",
		Tag:           "bytes,1888,opt,name=pdbm",
		Filename:      "protodb.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*PDBField)(nil),
		Field:         1888,
		Name:          "protodb.pdb",
		Tag:           "bytes,1888,opt,name=pdb",
		Filename:      "protodb.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional protodb.PDBFile pdbf = 1888;
	E_Pdbf = &file_protodb_proto_extTypes[0]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional protodb.PDBMsg pdbm = 1888;
	E_Pdbm = &file_protodb_proto_extTypes[1]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional protodb.PDBField pdb = 1888;
	E_Pdb = &file_protodb_proto_extTypes[2]
)

var File_protodb_proto protoreflect.FileDescriptor

const file_protodb_proto_rawDesc = "" +
	"\n" +
	"\rprotodb.proto\x12\aprotodb\x1a google/protobuf/descriptor.proto\"A\n" +
	"\aPDBFile\x12\x1c\n" +
	"\tNameStyle\x18\x01 \x01(\tR\tNameStyle\x12\x18\n" +
	"\aComment\x18\x02 \x03(\tR\aComment\"\x80\x02\n" +
	"\x06PDBMsg\x12\x18\n" +
	"\aComment\x18\x01 \x03(\tR\aComment\x12\x1e\n" +
	"\n" +
	"SQLPrepend\x18\x02 \x03(\tR\n" +
	"SQLPrepend\x12\x1c\n" +
	"\tSQLAppend\x18\x03 \x03(\tR\tSQLAppend\x12(\n" +
	"\x0fSQLAppendsAfter\x18\x04 \x03(\tR\x0fSQLAppendsAfter\x12$\n" +
	"\rSQLAppendsEnd\x18\x05 \x03(\tR\rSQLAppendsEnd\x12\x18\n" +
	"\aMsgList\x18\x06 \x01(\x05R\aMsgList\x12\x14\n" +
	"\x05NotDB\x18\a \x01(\bR\x05NotDB\x12\x1e\n" +
	"\n" +
	"SQLMigrate\x18\b \x03(\tR\n" +
	"SQLMigrate\"\xf0\x03\n" +
	"\bPDBField\x12\x14\n" +
	"\x05NotDB\x18\x01 \x01(\bR\x05NotDB\x12\x18\n" +
	"\aPrimary\x18\x02 \x01(\bR\aPrimary\x12\x16\n" +
	"\x06Unique\x18\x03 \x01(\bR\x06Unique\x12\x18\n" +
	"\aNotNull\x18\x04 \x01(\bR\aNotNull\x12\x1c\n" +
	"\tReference\x18\x05 \x01(\tR\tReference\x12\"\n" +
	"\fDefaultValue\x18\x06 \x01(\tR\fDefaultValue\x12\x1c\n" +
	"\tSQLAppend\x18\a \x03(\tR\tSQLAppend\x12$\n" +
	"\rSQLAppendsEnd\x18\b \x03(\tR\rSQLAppendsEnd\x12\x1a\n" +
	"\bNoUpdate\x18\t \x01(\bR\bNoUpdate\x12\x1e\n" +
	"\n" +
	"SerialType\x18\n" +
	" \x01(\x05R\n" +
	"SerialType\x12,\n" +
	"\x06DbType\x18\v \x01(\x0e2\x14.protodb.FieldDbTypeR\x06DbType\x12\x1c\n" +
	"\tDbTypeStr\x18\f \x01(\tR\tDbTypeStr\x12\x1e\n" +
	"\n" +
	"ZeroAsNull\x18\r \x01(\bR\n" +
	"ZeroAsNull\x12\x1a\n" +
	"\bNoInsert\x18\x0e \x01(\bR\bNoInsert\x12\x18\n" +
	"\aComment\x18\x0f \x03(\tR\aComment\x12\x1e\n" +
	"\n" +
	"UniqueName\x18\x10 \x01(\tR\n" +
	"UniqueName\"\x9e\x03\n" +
	"\aCrudReq\x12(\n" +
	"\x04Code\x18\x01 \x01(\x0e2\x14.protodb.CrudReqCodeR\x04Code\x127\n" +
	"\n" +
	"ResultType\x18\x02 \x01(\x0e2\x17.protodb.CrudResultTypeR\n" +
	"ResultType\x12\x1e\n" +
	"\n" +
	"SchemeName\x18\x03 \x01(\tR\n" +
	"SchemeName\x12\x1c\n" +
	"\tTableName\x18\x04 \x01(\tR\tTableName\x12\x1a\n" +
	"\bMsgBytes\x18\x05 \x01(\fR\bMsgBytes\x12\x1c\n" +
	"\tMsgFormat\x18\x06 \x01(\x05R\tMsgFormat\x12&\n" +
	"\x0eMsgLastFieldNo\x18\a \x01(\x05R\x0eMsgLastFieldNo\x120\n" +
	"\x13PartialUpdateFields\x18\b \x03(\tR\x13PartialUpdateFields\x12.\n" +
	"\x12SelectResultFields\x18\t \x03(\tR\x12SelectResultFields\x12.\n" +
	"\x12SelectOneKeyFields\x18\n" +
	" \x03(\tR\x12SelectOneKeyFields\"\xaa\x01\n" +
	"\bCrudResp\x12\"\n" +
	"\fRowsAffected\x18\x01 \x01(\x03R\fRowsAffected\x12\x18\n" +
	"\aErrInfo\x18\x02 \x01(\tR\aErrInfo\x12 \n" +
	"\vOldMsgBytes\x18\x03 \x01(\fR\vOldMsgBytes\x12 \n" +
	"\vNewMsgBytes\x18\x04 \x01(\fR\vNewMsgBytes\x12\x1c\n" +
	"\tMsgFormat\x18\b \x01(\x05R\tMsgFormat\"\x8a\x05\n" +
	"\rTableQueryReq\x12\x1e\n" +
	"\n" +
	"SchemeName\x18\x01 \x01(\tR\n" +
	"SchemeName\x12\x1c\n" +
	"\tTableName\x18\x02 \x01(\tR\tTableName\x12,\n" +
	"\x11ResultColumnNames\x18\x03 \x03(\tR\x11ResultColumnNames\x127\n" +
	"\x05Where\x18\x04 \x03(\v2!.protodb.TableQueryReq.WhereEntryR\x05Where\x12\x14\n" +
	"\x05Limit\x18\x05 \x01(\x05R\x05Limit\x12\x16\n" +
	"\x06Offset\x18\x06 \x01(\x03R\x06Offset\x12(\n" +
	"\x0fPreferBatchSize\x18\a \x01(\x05R\x0fPreferBatchSize\x12\x1c\n" +
	"\tMsgFormat\x18\b \x01(\x05R\tMsgFormat\x12R\n" +
	"\x0eWhere2Operator\x18\t \x03(\v2*.protodb.TableQueryReq.Where2OperatorEntryR\x0eWhere2Operator\x12:\n" +
	"\x06Where2\x18\n" +
	" \x03(\v2\".protodb.TableQueryReq.Where2EntryR\x06Where2\x1a8\n" +
	"\n" +
	"WhereEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aY\n" +
	"\x13Where2OperatorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\x0e2\x16.protodb.WhereOperatorR\x05value:\x028\x01\x1a9\n" +
	"\vWhere2Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa1\x01\n" +
	"\tQueryResp\x12\x1e\n" +
	"\n" +
	"ResponseNo\x18\x01 \x01(\x03R\n" +
	"ResponseNo\x12 \n" +
	"\vResponseEnd\x18\x02 \x01(\bR\vResponseEnd\x12\x18\n" +
	"\aErrInfo\x18\x03 \x01(\tR\aErrInfo\x12\x1a\n" +
	"\bMsgBytes\x18\x04 \x03(\fR\bMsgBytes\x12\x1c\n" +
	"\tMsgFormat\x18\b \x01(\x05R\tMsgFormat\"\xfc\x04\n" +
	"\bQueryReq\x12\x1c\n" +
	"\tQueryName\x18\x01 \x01(\tR\tQueryName\x12,\n" +
	"\x11ResultColumnNames\x18\x03 \x03(\tR\x11ResultColumnNames\x122\n" +
	"\x05Where\x18\x04 \x03(\v2\x1c.protodb.QueryReq.WhereEntryR\x05Where\x12$\n" +
	"\rWhereMsgBytes\x18\x05 \x01(\fR\rWhereMsgBytes\x12\x14\n" +
	"\x05Limit\x18\x06 \x01(\x05R\x05Limit\x12\x16\n" +
	"\x06Offset\x18\a \x01(\x03R\x06Offset\x12(\n" +
	"\x0fPreferBatchSize\x18\b \x01(\x05R\x0fPreferBatchSize\x12\x1c\n" +
	"\tMsgFormat\x18\t \x01(\x05R\tMsgFormat\x12M\n" +
	"\x0eWhere2Operator\x18\n" +
	" \x03(\v2%.protodb.QueryReq.Where2OperatorEntryR\x0eWhere2Operator\x125\n" +
	"\x06Where2\x18\v \x03(\v2\x1d.protodb.QueryReq.Where2EntryR\x06Where2\x1a8\n" +
	"\n" +
	"WhereEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aY\n" +
	"\x13Where2OperatorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\x0e2\x16.protodb.WhereOperatorR\x05value:\x028\x01\x1a9\n" +
	"\vWhere2Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xac\x01\n" +
	"\vFieldDbType\x12\r\n" +
	"\tAutoMatch\x10\x00\x12\b\n" +
	"\x04BOOL\x10\x01\x12\t\n" +
	"\x05INT32\x10\x02\x12\t\n" +
	"\x05INT64\x10\x03\x12\t\n" +
	"\x05FLOAT\x10\x04\x12\n" +
	"\n" +
	"\x06DOUBLE\x10\x05\x12\b\n" +
	"\x04TEXT\x10\x06\x12\t\n" +
	"\x05JSONB\x10\a\x12\b\n" +
	"\x04UUID\x10\b\x12\r\n" +
	"\tTIMESTAMP\x10\t\x12\b\n" +
	"\x04DATE\x10\n" +
	"\x12\t\n" +
	"\x05BYTEA\x10\v\x12\b\n" +
	"\x04INET\x10\f\x12\n" +
	"\n" +
	"\x06UINT32\x10\r*^\n" +
	"\vCrudReqCode\x12\n" +
	"\n" +
	"\x06INSERT\x10\x00\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x01\x12\x11\n" +
	"\rPARTIALUPDATE\x10\x02\x12\n" +
	"\n" +
	"\x06DELETE\x10\x03\x12\r\n" +
	"\tSELECTONE\x10\x04\x12\t\n" +
	"\x05QUERY\x10\x05*@\n" +
	"\x0eCrudResultType\x12\r\n" +
	"\tDMLResult\x10\x00\x12\n" +
	"\n" +
	"\x06NewMsg\x10\x01\x12\x13\n" +
	"\x0fOldMsgAndNewMsg\x10\x02*\xf8\x01\n" +
	"\rWhereOperator\x12\x0f\n" +
	"\vWOP_UNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06WOP_GT\x10\x01\x12\n" +
	"\n" +
	"\x06WOP_LT\x10\x02\x12\v\n" +
	"\aWOP_GTE\x10\x03\x12\v\n" +
	"\aWOP_LTE\x10\x04\x12\f\n" +
	"\bWOP_LIKE\x10\x05\x12\n" +
	"\n" +
	"\x06WOP_EQ\x10\x06\x12\x10\n" +
	"\fWOP_CONTAINS\x10\a\x12\x0f\n" +
	"\vWOP_OVERLAP\x10\b\x12\x14\n" +
	"\x10WOP_CONTAINS_ALL\x10\t\x12\x0e\n" +
	"\n" +
	"WOP_LEN_GT\x10\n" +
	"\x12\x0f\n" +
	"\vWOP_LEN_GTE\x10\v\x12\x0e\n" +
	"\n" +
	"WOP_LEN_LT\x10\f\x12\x0f\n" +
	"\vWOP_LEN_LTE\x10\r\x12\x0f\n" +
	"\vWOP_HAS_KEY\x10\x0e2\xad\x01\n" +
	"\n" +
	"ProtoDbSrv\x12-\n" +
	"\x04Crud\x12\x10.protodb.CrudReq\x1a\x11.protodb.CrudResp\"\x00\x12<\n" +
	"\n" +
	"TableQuery\x12\x16.protodb.TableQueryReq\x1a\x12.protodb.QueryResp\"\x000\x01\x122\n" +
	"\x05Query\x12\x11.protodb.QueryReq\x1a\x12.protodb.QueryResp\"\x000\x01:F\n" +
	"\x04pdbf\x12\x1c.google.protobuf.FileOptions\x18\xe0\x0e \x01(\v2\x10.protodb.PDBFileR\x04pdbf\x88\x01\x01:H\n" +
	"\x04pdbm\x12\x1f.google.protobuf.MessageOptions\x18\xe0\x0e \x01(\v2\x0f.protodb.PDBMsgR\x04pdbm\x88\x01\x01:F\n" +
	"\x03pdb\x12\x1d.google.protobuf.FieldOptions\x18\xe0\x0e \x01(\v2\x11.protodb.PDBFieldR\x03pdb\x88\x01\x01B\x1aZ\x18github.com/ygrpc/protodbb\x06proto3"

var (
	file_protodb_proto_rawDescOnce sync.Once
	file_protodb_proto_rawDescData []byte
)

func file_protodb_proto_rawDescGZIP() []byte {
	file_protodb_proto_rawDescOnce.Do(func() {
		file_protodb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protodb_proto_rawDesc), len(file_protodb_proto_rawDesc)))
	})
	return file_protodb_proto_rawDescData
}

var file_protodb_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_protodb_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_protodb_proto_goTypes = []any{
	(FieldDbType)(0),                    // 0: protodb.FieldDbType
	(CrudReqCode)(0),                    // 1: protodb.CrudReqCode
	(CrudResultType)(0),                 // 2: protodb.CrudResultType
	(WhereOperator)(0),                  // 3: protodb.WhereOperator
	(*PDBFile)(nil),                     // 4: protodb.PDBFile
	(*PDBMsg)(nil),                      // 5: protodb.PDBMsg
	(*PDBField)(nil),                    // 6: protodb.PDBField
	(*CrudReq)(nil),                     // 7: protodb.CrudReq
	(*CrudResp)(nil),                    // 8: protodb.CrudResp
	(*TableQueryReq)(nil),               // 9: protodb.TableQueryReq
	(*QueryResp)(nil),                   // 10: protodb.QueryResp
	(*QueryReq)(nil),                    // 11: protodb.QueryReq
	nil,                                 // 12: protodb.TableQueryReq.WhereEntry
	nil,                                 // 13: protodb.TableQueryReq.Where2OperatorEntry
	nil,                                 // 14: protodb.TableQueryReq.Where2Entry
	nil,                                 // 15: protodb.QueryReq.WhereEntry
	nil,                                 // 16: protodb.QueryReq.Where2OperatorEntry
	nil,                                 // 17: protodb.QueryReq.Where2Entry
	(*descriptorpb.FileOptions)(nil),    // 18: google.protobuf.FileOptions
	(*descriptorpb.MessageOptions)(nil), // 19: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 20: google.protobuf.FieldOptions
}
var file_protodb_proto_depIdxs = []int32{
	0,  // 0: protodb.PDBField.DbType:type_name -> protodb.FieldDbType
	1,  // 1: protodb.CrudReq.Code:type_name -> protodb.CrudReqCode
	2,  // 2: protodb.CrudReq.ResultType:type_name -> protodb.CrudResultType
	12, // 3: protodb.TableQueryReq.Where:type_name -> protodb.TableQueryReq.WhereEntry
	13, // 4: protodb.TableQueryReq.Where2Operator:type_name -> protodb.TableQueryReq.Where2OperatorEntry
	14, // 5: protodb.TableQueryReq.Where2:type_name -> protodb.TableQueryReq.Where2Entry
	15, // 6: protodb.QueryReq.Where:type_name -> protodb.QueryReq.WhereEntry
	16, // 7: protodb.QueryReq.Where2Operator:type_name -> protodb.QueryReq.Where2OperatorEntry
	17, // 8: protodb.QueryReq.Where2:type_name -> protodb.QueryReq.Where2Entry
	3,  // 9: protodb.TableQueryReq.Where2OperatorEntry.value:type_name -> protodb.WhereOperator
	3,  // 10: protodb.QueryReq.Where2OperatorEntry.value:type_name -> protodb.WhereOperator
	18, // 11: protodb.pdbf:extendee -> google.protobuf.FileOptions
	19, // 12: protodb.pdbm:extendee -> google.protobuf.MessageOptions
	20, // 13: protodb.pdb:extendee -> google.protobuf.FieldOptions
	4,  // 14: protodb.pdbf:type_name -> protodb.PDBFile
	5,  // 15: protodb.pdbm:type_name -> protodb.PDBMsg
	6,  // 16: protodb.pdb:type_name -> protodb.PDBField
	7,  // 17: protodb.ProtoDbSrv.Crud:input_type -> protodb.CrudReq
	9,  // 18: protodb.ProtoDbSrv.TableQuery:input_type -> protodb.TableQueryReq
	11, // 19: protodb.ProtoDbSrv.Query:input_type -> protodb.QueryReq
	8,  // 20: protodb.ProtoDbSrv.Crud:output_type -> protodb.CrudResp
	10, // 21: protodb.ProtoDbSrv.TableQuery:output_type -> protodb.QueryResp
	10, // 22: protodb.ProtoDbSrv.Query:output_type -> protodb.QueryResp
	20, // [20:23] is the sub-list for method output_type
	17, // [17:20] is the sub-list for method input_type
	14, // [14:17] is the sub-list for extension type_name
	11, // [11:14] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_protodb_proto_init() }
func file_protodb_proto_init() {
	if File_protodb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protodb_proto_rawDesc), len(file_protodb_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   14,
			NumExtensions: 3,
			NumServices:   1,
		},
		GoTypes:           file_protodb_proto_goTypes,
		DependencyIndexes: file_protodb_proto_depIdxs,
		EnumInfos:         file_protodb_proto_enumTypes,
		MessageInfos:      file_protodb_proto_msgTypes,
		ExtensionInfos:    file_protodb_proto_extTypes,
	}.Build()
	File_protodb_proto = out.File
	file_protodb_proto_goTypes = nil
	file_protodb_proto_depIdxs = nil
}
